// NOTE: This file has been automatically generated by github.com/aacfactory/gcg. Don't Edit it.

package modules

import (
	"github.com/aacfactory/fns-example/standalone/modules/examples"
	"github.com/aacfactory/fns/services"
)

func Services() (v []services.Service) {
	v = append(
		dependencies(),
		endpoints()...,
	)
	v = append(v, examples.Service())
	return
}

func dependencies() (v []services.Service) {
	v = []services.Service{
		// add dependencies here
	}
	return
}
