name: users
runtime:
  maxWorkers: 262144
  workerMaxIdleSeconds: 10
  handleTimeoutSeconds: 10
log:
  level: info
  formatter: console
oas:
  title: users
server:
  port: 8800
authorizations:
  encoding:
    method: RS512
    publicKey: ./config/jwt/pub.pem
    privateKey: ./config/jwt/pri.pem
    issuer: fns
    expirations: 720h0m0s
