log:
  level: warn
  formatter: json
server:
  port: 8800
cluster:
  devMode: false
  nodesProxyAddress: ""
  kind: members
  client:
    maxIdleConnSeconds: 60
    requestTimeoutSeconds: 10
  options:
    members:
    - ip:port
