name: standalone
service:
  maxWorkers: 0
  workerMaxIdleSeconds: 10
  handleTimeoutSeconds: 10
log:
  level: info
  formatter: console
  color: true
server:
  port: 80
oas:
  title: Standalone
  description: |
    Standalone server description
  terms: https://terms.fns
  contact:
    name: hello
    url: https://hello.fns
    email: hello@fns
  license:
    name: license
    url: https://license.fns
  servers:
    - url: https://test.hello.fns
      description: test
    - url: https://hello.fns
      description: prod