log:
  level: debug
  formatter: console
  color: true
server:
  port: 8800
sql:
  driver: postgres
  masterSlaverMode: false
  dsn:
  - dsn
  maxIdles: 2
  maxOpens: 4
  enableDebugLog: false
  gtmCleanUpSecond: 60
  isolation: 2
