name: standalone
log:
  level: info
  formatter: console
oas:
  title: standalone
server:
  port: 8800
authorizations:
  encoding:
    method: RS512
    publicKey: ./config/jwt/pub.pem
    privateKey: ./config/jwt/pri.pem
    issuer: fns
    expirations: 720h0m0s
