// NOTE: This file has been automatically generated by github.com/aacfactory/gcg. Dont Edit it.

package modules

import (
	"github.com/aacfactory/fns-example/cluster/posts/modules/posts"
	"github.com/aacfactory/fns/service"
)

func Services() (services []service.Service) {
	services = append(
		services,
		dependencies()...,
	)
	services = append(
		services,
		posts.Service(),
	)
	return
}
