// NOTE: This file has been automatically generated by github.com/aacfactory/gcg. Dont Edit it.

// Package repository
// write data repository here
// see https://github.com/aacfactory/fns-contrib/tree/main/databases/sql
package repository
